# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/game.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'proto/game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/game.proto\"\xcb\x04\n\x08GameInfo\x12#\n\x08\x63\x61r_info\x18\x01 \x01(\x0b\x32\x11.GameInfo.CarInfo\x12\'\n\ntrack_info\x18\x02 \x01(\x0b\x32\x13.GameInfo.TrackInfo\x1a\x80\x03\n\x07\x43\x61rInfo\x12\r\n\x05x_pos\x18\x01 \x01(\x05\x12\r\n\x05y_pos\x18\x02 \x01(\x05\x12\r\n\x05z_pos\x18\x03 \x01(\x05\x12\x19\n\x11\x61pplied_direction\x18\x04 \x01(\r\x12\x1a\n\x12intended_direction\x18\x05 \x01(\r\x12\r\n\x05speed\x18\x06 \x01(\x05\x12\x0b\n\x03rpm\x18\x07 \x01(\r\x12\x0c\n\x04gear\x18\x08 \x01(\r\x12\x14\n\x0cgear_timeout\x18\t \x01(\r\x12\x1a\n\x12\x61\x63\x63\x65l_lifted_timer\x18\n \x01(\r\x12\x10\n\x08\x63ollided\x18\r \x01(\x08\x12\x18\n\x10traction_loss_fl\x18\x0e \x01(\x08\x12\x18\n\x10traction_loss_fr\x18\x0f \x01(\x08\x12\x18\n\x10traction_loss_rl\x18\x10 \x01(\x08\x12\x18\n\x10traction_loss_rr\x18\x11 \x01(\x08\x12\x11\n\twrong_way\x18\x12 \x01(\x08\x12\x11\n\tfree_fall\x18\x13 \x01(\x08\x12\x15\n\rdrift_timeout\x18\x14 \x01(\r\x1an\n\tTrackInfo\x12\x10\n\x08track_id\x18\x01 \x01(\r\x12\x14\n\x0ctrack_status\x18\x02 \x01(\r\x12\x14\n\x0clap_progress\x18\x03 \x01(\x05\x12\x16\n\x0etrack_progress\x18\x04 \x01(\x05\x12\x0b\n\x03lap\x18\x05 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMEINFO']._serialized_start=21
  _globals['_GAMEINFO']._serialized_end=608
  _globals['_GAMEINFO_CARINFO']._serialized_start=112
  _globals['_GAMEINFO_CARINFO']._serialized_end=496
  _globals['_GAMEINFO_TRACKINFO']._serialized_start=498
  _globals['_GAMEINFO_TRACKINFO']._serialized_end=608
# @@protoc_insertion_point(module_scope)
